from django.conf.urls import patterns, include, url

urlpatterns = patterns('appsistema.views',
                       url(r'^cola/$', 'cola', name='cola'),
                       url(r'^detalles/(\d+)', 'detalles_solicitud', name='detalles_solicitud'),
                       url(r'^iniciar/(\d+)', 'iniciar_solicitud', name='iniciar_solicitud'),
                       url(r'^pausar/(\d+)', 'pausar_solicitud', name='iniciar_solicitud'),
                       url(r'^terminar/(\d+)', 'terminar_solicitud', name='terminar_solicitud'),
                       url(r'^crear-solicitud/$', 'crear_solicitud', name='crear_solicitud'),
                       url(r'^reasignar-solicitud/$', 'reasignar_solicitud', name='reasignar_solicitud'),
                       url(r'^ver-cola/$', 'ver_cola', name='ver_cola'),
                       url(r'^agregar-comentario/(\d+)', 'agregar_comentario', name='agregar_comentario'),
                       url(r'^aprobar-comentario/', 'aprobar_comentario', name='aprobar_comentario'),
                       url(r'^ver-estadisticas/$', 'ver_estadisticas', name='ver_estadisticas'),
                       url(r'^calificar-solicitud/', 'calificar', name='calificar'),
                       url(r'^accion-realizada/(?P<accion>[^\.]+)/$', 'accion_correcta', name='accion_correcta'),
                       url(r'^estadistica_categoria/$', 'estadisticas_categoria', name='estadisticas_categoria'),
                       url(r'^estadistica_tipo/$', 'estadisticas_tipo', name='estadisticas_tipo'),
                       url(r'^numero_solicitudes/$', 'estadisticas_solicitudes', name='estadisticas_solicitudes'),
                       url(r'^estadistica_estado/$', 'estadistica_estado', name='estadistica_estado'),
                       url(r'^estadistica_incidente/$', 'estadistica_incidente', name='estadistica_incidente'),
                       url(r'^estadistica_feed/$', 'estadistica_feed', name='estadistica_feed'),
                       url(r'^estadistica_empleado/$', 'estadistica_empleado', name='estadistica_empleado'),
                       url(r'^estadistica_turnos/$', 'estadistica_turnos', name='estadistica_turnos'),
)